error: Add code for threshold config validation
This commit adds a new warning code for threshold config file validation
failures.

(cherry picked from commit cb03455c0412d6af4c8804337c2f7fb145cd93a9)