pfring: copy cflags over from src/
This should cause the following warning to error out:

runmode-pfring.c: In function 'OldParsePfringConfig':
runmode-pfring.c:118:17: error: implicit declaration of function 'StringParseUnt16'; did you mean 'StringParseInt16'? [-Wimplicit-function-declaration]
  118 |             if (StringParseUnt16(&pfconf->threads, 10, 0, threadsstr) < 0) {
      |                 ^~~~~~~~~~~~~~~~
      |                 StringParseInt16

Ticket: #8271