exception: rename fn for converting 'auto' value
This function is meant to decide what policy should be chosen when
an exception policy is set to auto in the configure file.

Related to
Bug #6169