exception: fix use of master switch with default
If an exception policy wasn't set up individually, check that the master
switch policy was defined before setting up to auto.

Bug #6169