suricata: fix clang shadow declaration
The commit d4a5406 make suricata instance as
global variable and building the code with clang
fires up the error below:

suricata.c:376:40: error: declaration shadows a variable in the global scope
static void GlobalsDestroy(SCInstance *suri)
                                       ^
suricata.c:237:12: note: previous declaration is here
SCInstance suri;

This patch rename 'suri' with 'suricata' to avoid shadow declaration.